#define _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <sys.h>
#include <time.h>

#ifndef DEFAULT_PORT_MODE
#define DEFAULT_PORT_MODE PORT_MODE_IN_HIZ
#endif

#if DEFAULT_PORT_MODE == PORT_MODE_IO_PUP
#define INIT_PORT(p) P##p##M0 = P##p##M1 = 0x00
#elif DEFAULT_PORT_MODE == PORT_MODE_OUT_PP
#define INIT_PORT(p) P##p##M0 = 0xFF, P##p##M1 = 0x00
#elif DEFAULT_PORT_MODE == PORT_MODE_IN_HIZ
#define INIT_PORT(p) P##p##M0 = 0x00, P##p##M1 = 0xFF
#elif DEFAULT_PORT_MODE == PORT_MODE_OUT_OD
#define INIT_PORT(p) P##p##M0 = 0xFF, P##p##M1 = 0xFF
#else
#error "Invalid DEFAULT_PORT_MODE"
#endif

#define INIT_PORTS_0()
#define INIT_PORTS_1() INIT_PORT(0)
#define INIT_PORTS_2() INIT_PORTS_1(); INIT_PORT(1)
#define INIT_PORTS_3() INIT_PORTS_2(); INIT_PORT(2)
#define INIT_PORTS_4() INIT_PORTS_3(); INIT_PORT(3)
#define INIT_PORTS_5() INIT_PORTS_4(); INIT_PORT(4)
#define INIT_PORTS_6() INIT_PORTS_5(); INIT_PORT(5)
#define INIT_PORTS_7() INIT_PORTS_6(); INIT_PORT(6)
#define INIT_PORTS_8() INIT_PORTS_7(); INIT_PORT(7)
#define INIT_PORTS_9() INIT_PORTS_8(); INIT_PORT(8)
#define INIT_PORTS_10() INIT_PORTS_9(); INIT_PORT(9)
#define _INIT_PORTS(n) INIT_PORTS_##n()
#define INIT_PORTS(n) _INIT_PORTS(n)

#define PRINT_PORT(p) printf("        P" #p "M0 = 0x%02X; \\\n        P" #p "M1 = 0x%02X; \\\n", P##p##M0, P##p##M1);
#define PRINT_PORTS_0()
#define PRINT_PORTS_1() PRINT_PORT(0)
#define PRINT_PORTS_2() PRINT_PORTS_1(); PRINT_PORT(1)
#define PRINT_PORTS_3() PRINT_PORTS_2(); PRINT_PORT(2)
#define PRINT_PORTS_4() PRINT_PORTS_3(); PRINT_PORT(3)
#define PRINT_PORTS_5() PRINT_PORTS_4(); PRINT_PORT(4)
#define PRINT_PORTS_6() PRINT_PORTS_5(); PRINT_PORT(5)
#define PRINT_PORTS_7() PRINT_PORTS_6(); PRINT_PORT(6)
#define PRINT_PORTS_8() PRINT_PORTS_7(); PRINT_PORT(7)
#define PRINT_PORTS_9() PRINT_PORTS_8(); PRINT_PORT(8)
#define PRINT_PORTS_10() PRINT_PORTS_9(); PRINT_PORT(9)
#define _PRINT_PORTS(n) PRINT_PORTS_##n()
#define PRINT_PORTS(n) _PRINT_PORTS(n)

int main() {
	INIT_PORTS(PORT_COUNT);

#define XX(port, pin, mode, name) pin_mode(port, pin, mode);
	GPIO_TABLES_MAP(XX)
#undef XX


	// char time_buf[32];
	// time_t now = time(NULL);
	// struct tm* tm_info = localtime(&now);
	// strftime(time_buf, sizeof(time_buf), "%Y-%m-%d %H:%M:%S", tm_info);
	// printf("/* Generated by c51io.sh on %s, don't modify this file manually. */\n\n", time_buf);

	printf("/* Generated by c51io.sh, don't modify this file manually. */\n\n");

	printf("\
#ifndef __GPIO_H__\n\
#define __GPIO_H__\n\
\n\
#include \"sys.h\"\n\
\n\
#define gpio_init()  \\\n\
    do {             \\\n\
");

	PRINT_PORTS(PORT_COUNT);

	printf("\
    } while (0)\n\
\n\
#endif /* __GPIO_H__ */\n\
");

	return 0;
}
