/* Generated by c51io.sh, don't modify this file manually. */

#ifndef __GPIO_H__
#define __GPIO_H__

#include "sys.h"

#define gpio_init()                  \
    do {                             \
        P0M0 = 0x00; /* 0000,0000 */ \
        P0M1 = 0xFF; /* 1111,1111 */ \
        P1M0 = 0x00; /* 0000,0000 */ \
        P1M1 = 0xFF; /* 1111,1111 */ \
        P2M0 = 0x00; /* 0000,0000 */ \
        P2M1 = 0xFE; /* 1111,1110 */ \
        P3M0 = 0x00; /* 0000,0000 */ \
        P3M1 = 0xFB; /* 1111,1011 */ \
    } while (0)

#endif /* __GPIO_H__ */
