#ifndef __VERSION_H__
#define __VERSION_H__

#define LDR_VERSION_MAJOR 1
#define LDR_VERSION_MINOR 0
#define LDR_VERSION_PATCH 0
#define LDR_VERSION (((uint32_t)LDR_VERSION_MAJOR << 24) | ((uint32_t)LDR_VERSION_MINOR << 16) | (LDR_VERSION_PATCH))
#define LDR_VERSION_NO_PATCH (((uint16_t)LDR_VERSION_MAJOR << 8) | (LDR_VERSION_MINOR))

#endif /* __VERSION_H__ */
