#!/bin/bash

set -e

CURRENT_DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd ${CURRENT_DIR}

CRC=${CURRENT_DIR}/../programmer/Release/crc.exe
APP_HEX=${CURRENT_DIR}/../demo_app/output/DEMO_APP.hex
COMMON_H=${CURRENT_DIR}/../common.h
ISR_ASM=${CURRENT_DIR}/src/isr.asm
LDR_SIZE=$(grep -oP '#define LDR_SIZE \K[0x0-9A-F]+' ${COMMON_H})
echo "LDR_SIZE=${LDR_SIZE}"

rm -rf ./output || true

# 0. update isr.asm
# convert the LDR_SIZE from `0xXXXX` to `XXXXH`
LDR_SIZE_HEX=$(printf "%04XH" ${LDR_SIZE})
echo "LDR_SIZE_HEX=${LDR_SIZE_HEX}"
# replace LDR_SIZE in ISR_ASM like `LDR_SIZE EQU 1000H`
sed -i "s/LDR_SIZE EQU .*/LDR_SIZE EQU ${LDR_SIZE_HEX}/" ${ISR_ASM}

# 1. calculate app crc32 and update common.h
set +e
output=`${CRC} -i ${APP_HEX} -a crc32 -l ${LDR_SIZE} -f 0x00`
if [ $? -ne 0 ]; then
    exit 1
fi
set -e
# 将输出读入数组
IFS=' ' read -ra values <<< "$output"

# 检查数组元素数量
if [ ${#values[@]} -lt 2 ]; then
    echo "Error: Expected at least two values" >&2
    exit 1
fi

app_crc32="${values[0]}"
app_size="${values[1]}"
app_crc32="0x${app_crc32}"
app_size="0x${app_size}"
echo "APP crc32 is ${app_crc32}, APP size is ${app_size}"
app_crc32="${app_crc32}   // CRC32 of app binary, generated by bootloader/make.sh"
sed -i "s|#define APP_CRC .*|#define APP_CRC ${app_crc32}|" ${COMMON_H}
app_size="${app_size}  // Size of app binary, generated by bootloader/make.sh"
sed -i "s|#define APP_SIZE .*|#define APP_SIZE ${app_size}|" ${COMMON_H}

exit

time make DEBUG=1 -j

