#!/bin/bash

set -e

CURRENT_DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd ${CURRENT_DIR}

CRC=${CURRENT_DIR}/../programmer/Release/crc.exe
APP_HEX=${CURRENT_DIR}/../app/output/APP.hex
COMMON_H=${CURRENT_DIR}/../common/common.h
ISR_ASM=${CURRENT_DIR}/src/isr.asm
LDR_SIZE=$(grep -oP '#define LDR_SIZE \K[0x0-9A-F]+' ${COMMON_H})
STC_RAM_SIZE=$(grep -oP '#define STC_RAM_SIZE \K[0x0-9A-F]+' ${COMMON_H})
STC_ROM_SIZE=$(grep -oP '#define STC_ROM_SIZE \K[0x0-9A-F]+' ${COMMON_H})
RAM_SIZE=`printf "%d" ${STC_RAM_SIZE}` # convert 0xXXXX to decimal
ROM_SIZE=`printf "%d" ${STC_ROM_SIZE}` # convert 0xXXXX to decimal
LDR_SIZE_10=`printf "%d" ${LDR_SIZE}`  # convert 0xXXXX to decimal
echo "LDR_SIZE=${LDR_SIZE}"
echo "STC_RAM_SIZE=${STC_RAM_SIZE}, ${RAM_SIZE}"
echo "STC_ROM_SIZE=${STC_ROM_SIZE}, ${ROM_SIZE}"
# exit
rm -rf ./output || true

# 0. update isr.asm
# convert the LDR_SIZE from `0xXXXX` to `XXXXH`
LDR_SIZE_HEX=$(printf "%04XH" ${LDR_SIZE})
echo "LDR_SIZE_HEX=${LDR_SIZE_HEX}"
# replace LDR_SIZE in ISR_ASM like `LDR_SIZE EQU 1000H`
sed -i "s/LDR_SIZE EQU .*/LDR_SIZE EQU ${LDR_SIZE_HEX}/" ${ISR_ASM}

# 1. calculate app crc32/size and update common.h
set +e
output=`${CRC} -i ${APP_HEX} -a crc32 -l ${LDR_SIZE} -f 0x00`
if [ $? -ne 0 ]; then
    exit 1
fi
set -e
IFS=' ' read -ra values <<< "$output"
if [ ${#values[@]} -lt 2 ]; then
    echo "Error: Expected at least two values" >&2
    exit 1
fi
app_crc32="${values[0]}"
app_size="${values[1]}"
app_crc32="0x${app_crc32}"
app_size="0x${app_size}"
echo "APP crc32 is ${app_crc32}, APP size is ${app_size}"
app_crc32="${app_crc32}   // CRC32 of app binary, generated by bootloader/make.sh"
sed -i "s|#define APP_CRC .*|#define APP_CRC ${app_crc32}|" ${COMMON_H}
app_size="${app_size}  // Size of app binary, generated by bootloader/make.sh"
sed -i "s|#define APP_SIZE .*|#define APP_SIZE ${app_size}|" ${COMMON_H}

# 2. build bootloader
time make DEBUG=1 -j

# 3. check bootloader size is not bigger than LDR_SIZE

# print a value, if its a integer, print it as integer, else keep 2 decimal places
printf_value() {
    local value=$1
    # 检查是否为整数（小数部分全为0）
    if [[ $(awk -v n="$value" 'BEGIN{print (n == int(n))}') -eq 1 ]]; then
        printf "%d\n" "$value"  # 输出整数
    else
        printf "%.2f\n" "$value"  # 输出两位小数
    fi
}

# take out the last line of ./buildlog.txt
log=`tail -n 1 buildLog.txt`
const=`echo "${log}" | awk '{print $5}' | awk -F '=' '{print $2}'`
code=`echo "${log}" | awk '{print $6}' | awk -F '=' '{print $2}'`
romsize=$((const+code))
kb=`echo $romsize | awk '{print $1 / 1024}'`
kb_total=`echo $LDR_SIZE_10 | awk '{print $1 / 1024}'`
# echo "first kb_total=$kb_total"
kb_total=`printf_value $kb_total`
# echo "second kb_total=$kb_total"
awk_param="{print (\$1 / ${LDR_SIZE_10}) * 100}"
used=`echo $romsize | awk "$awk_param"`
printf "ROM size: %d/%d, %.2fKB/%sKB, %.2f%% Full\n" $romsize "${LDR_SIZE_10}" $kb $kb_total $used | tee >(cat >&1) >> buildLog.txt

if [ $romsize -gt $LDR_SIZE_10 ]; then
    echo "Error: Bootloader size $romsize exceeds LDR_SIZE $LDR_SIZE_10" >&2
    exit 1
fi